//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtratimeActive
    {
        public long PID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Content { get; set; }
        public string Hour { get; set; }
        public string Participant { get; set; }
        public string Location { get; set; }
        public Nullable<long> KindActive { get; set; }
    }
}
