//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DOANTOTNGHIEPEntities : DbContext
    {
        public DOANTOTNGHIEPEntities()
            : base("name=DOANTOTNGHIEPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<ExtratimeActive> ExtratimeActives { get; set; }
        public virtual DbSet<PersonalExtratimeActive> PersonalExtratimeActives { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<WorkingDefine> WorkingDefines { get; set; }
        public virtual DbSet<WorkingDefineCate> WorkingDefineCates { get; set; }
    }
}
