//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalExtratimeActive
    {
        public long Pid { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string Location { get; set; }
        public string Proof { get; set; }
        public Nullable<long> KindActive { get; set; }
        public string TeacherCode { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
