//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public long PID { get; set; }
        public string USER { get; set; }
        public string PASSWORD { get; set; }
        public string TOKEN { get; set; }
        public string IPLOGIN { get; set; }
        public Nullable<long> STATUS { get; set; }
        public string SALT { get; set; }
        public string Role { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DayOfBirth { get; set; }
        public string Country { get; set; }
        public string CID { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Code { get; set; }
    }
}
