//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingDefine
    {
        public long Pid { get; set; }
        public Nullable<long> CatePid { get; set; }
        public string Content { get; set; }
        public int Value { get; set; }
    }
}
